apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "clamav.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clamav.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: clamd
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: CLAMAV_NO_FRESHCLAMD
              value: {{ .Values.env.noFreshclamd | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}