{{- if .Values.signaling.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}-signaling
data:
  server.conf: |
    [http]
    listen = 0.0.0.0:8080

    [appinfo]
    id = spreed

    [backend]
    backends = backend-1
    allowall = false
    timeout = 10
    connectionsperhost = 8

    [backend-1]
    url = {{ .Values.signaling.backend.url }}
    secret = {{ .Values.signaling.backend.secret }}

    [sessions]
    # Session secrets
    hashkey = {{ .Values.signaling.sessions.hashkey }}
    blockkey = {{ .Values.signaling.sessions.blockkey }}

    [mcu]
    type = {{ .Values.signaling.mcu.type }}
    url = ws://{{ .Values.signaling.mcu.url }}

    [turn]
    apikey = {{ .Values.signaling.turn.secret }}
    secret = {{ .Values.signaling.turn.secret }}
    servers = turn:{{ .Values.signaling.turn.server }}:3478?transport=udp,turn:{{ .Values.signaling.turn.server }}:3478?transport=tcp

    [nats]
    url = nats://{{ .Release.Name }}-nats:4222
{{- end -}}