{{- if .Values.nats.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nats
  labels:
    app: {{ .Release.Name }}-nats
spec:
  replicas: {{ .Values.nats.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nats
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image }}"
          imagePullPolicy: {{ .Values.nats.pullPolicy }}
          ports:
            - name: client
              containerPort: 4222
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nats
  labels:
    app: {{ .Release.Name }}-nats
spec:
  type: {{ .Values.nats.service.type }}
  ports:
    - port: {{ .Values.nats.service.port }}
      targetPort: client
      protocol: TCP
      name: client
  selector:
    app: {{ .Release.Name }}-nats
{{- end -}}