{{- if .Values.signaling.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-signaling
  labels:
    app: {{ .Release.Name }}-signaling
spec:
  replicas: {{ .Values.signaling.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-signaling
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-signaling
    spec:
      containers:
        - name: signaling
          image: {{ .Values.signaling.image }}
          ports:
            - containerPort: {{ .Values.signaling.service.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-signaling
  labels:
    app: {{ .Release.Name }}-signaling
spec:
  type: {{ .Values.signaling.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.signaling.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-signaling
{{- end -}}