apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-signaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signaling
  template:
    metadata:
      labels:
        app: signaling
    spec:
      containers:
        - name: signaling
          image: {{ .Values.images.signaling }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/v1/welcome
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/welcome
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: config
              mountPath: /config/server.conf
              subPath: server.conf
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-signaling
spec:
  selector:
    app: signaling
  ports:
    - port: 80
      targetPort: 8080